postgres:
  host: "localhost"
  port: 5432
  database: "postgres"
  user: "postgres"
  password: "1234"
redis:
  host: "localhost"
  port: 6379
  username: "default"
  password: "mysecretpassword"
auto-sync: 10m